name       : curl
version    : 7.71.1
release    : 62
source     :
    - https://github.com/curl/curl/releases/download/curl-7_71_1/curl-7.71.1.tar.xz : 40f83eda27cdbeb25cd4da48cefb639af1b9395d6026d2da1825bf059239658c
homepage   : https://curl.haxx.se/
license    : MIT
component  : system.base
emul32     : yes
summary    : Get a file from an HTTP, HTTPS or FTP server
description: |
    curl is a client to get files from servers using any of the supported protocols. The command is designed to work without user interaction or any kind of interactivity.  curl offers a busload of useful tricks like proxy support, user authentication, ftp upload, HTTP post, file transfer resume and more.
patterns   :
    - /usr/share/man
    - devel : /usr/share/aclocal/libcurl.m4
builddeps  :
    - pkgconfig32(com_err)
    - pkgconfig32(krb5)
    - pkgconfig32(libssh2)
    - pkgconfig32(zlib)
    - pkgconfig(libnghttp2)
    - groff
    - openssh-server
rundeps    :
    - devel :
        - kerberos-devel
        - libssh2-devel
        - nghttp2-devel
    - 32bit-devel :
        - kerberos-32bit-devel
        - libssh2-32bit-devel
setup      : |
    %reconfigure --disable-static \
                 --enable-threaded-resolver \
                 --without-gnutls \
                 --enable-libcurl-option \
                 --with-ca-path=/etc/ssl/certs \
                 --with-libssh2 \
                 --with-gssapi
build      : |
    %make
install    : |
    %make_install
check      : |
    %make -k check || :
