name       : curl
version    : 8.2.1
release    : 80
source     :
    - https://github.com/curl/curl/releases/download/curl-8_2_1/curl-8.2.1.tar.gz : f98bdb06c0f52bdd19e63c4a77b5eb19b243bcbbd0f5b002b9f3cba7295a3a42
homepage   : https://curl.haxx.se
license    : MIT
component  : system.base
emul32     : yes
summary    : Get a file from an HTTP, HTTPS or FTP server
description: |
    curl is a client to get files from servers using any of the supported protocols. The command is designed to work without user interaction or any kind of interactivity.  curl offers a busload of useful tricks like proxy support, user authentication, ftp upload, HTTP post, file transfer resume and more.
builddeps  :
    - pkgconfig32(com_err)
    - pkgconfig32(krb5)
    - pkgconfig32(libssh2)
    - pkgconfig32(libzstd)
    - pkgconfig32(openssl)
    - pkgconfig32(zlib)
    - pkgconfig(libnghttp2)
    - groff
    - openssh-server
    # temporary, remove after openssl 3.1 rebuilds
    - openssl-32bit-devel
rundeps    :
    - devel :
        - kerberos-devel
        - libssh2-devel
        - nghttp2-devel
    - 32bit-devel :
        - kerberos-32bit-devel
        - libssh2-32bit-devel
setup      : |
    %reconfigure --disable-static \
                 --enable-threaded-resolver \
                 --without-gnutls \
                 --enable-libcurl-option \
                 --with-ca-path=/etc/ssl/certs \
                 --with-libssh2 \
                 --with-openssl \
                 --with-gssapi
build      : |
    %make
    %make -C scripts
install    : |
    %make_install
    %make_install -C scripts
check      : |
    %make -k check
patterns   :
    - /usr/share/man
    - devel : /usr/share/aclocal/libcurl.m4
