name       : curl
version    : 7.54.1
release    : 30
source     :
    - https://curl.haxx.se/download/curl-7.54.1.tar.gz : cd404b808b253512dafec4fed0fb2cc98370d818a7991826c3021984fc27f9d0
homepage   : http://curl.haxx.se
license    : GPL-3.0
component  : system.base
summary    : Get a file from an HTTP, HTTPS or FTP server
description: |
    curl is a client to get files from servers using any of the supported protocols. The command is designed to work without user interaction or any kind of interactivity.  curl offers a busload of useful tricks like proxy support, user authentication, ftp upload, HTTP post, file transfer resume and more.
patterns   :
    - /usr/share/man
    - devel : /usr/share/aclocal/libcurl.m4
builddeps  :
    - pkgconfig32(libssh2)
    - pkgconfig32(libssl)
    - pkgconfig32(zlib)
    - pkgconfig(libnghttp2)
emul32     : yes
setup      : |
    %configure --disable-static \
               --enable-threaded-resolver \
               --without-gnutls \
               --enable-libcurl-option \
               --with-ca-bundle=/etc/ssl/certs/ca-certificates.crt \
               --with-libssh2
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
